# Generated by Django 5.2.1 on 2025-06-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_contactinfo_blogpost_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='social_links',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
