# Generated by Django 5.2.1 on 2025-06-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_contactinfo_social_links_contactinfo_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('paragraph1', models.TextField()),
                ('paragraph2', models.TextField()),
                ('paragraph3', models.TextField()),
                ('image_url', models.URLField()),
                ('card_title', models.CharField(max_length=255)),
                ('card_text', models.TextField()),
                ('button_label', models.CharField(max_length=100)),
            ],
        ),
    ]
