# Generated by Django 5.2.1 on 2025-06-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='button_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
