# Generated by Django 5.2.1 on 2025-06-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_aboutus_button_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(default='Unnamed', max_length=255),
        ),
    ]
