# Generated by Django 5.2.4 on 2025-07-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_contactinfo_address_contactinfo_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='conclusion',
            field=models.TextField(blank=True, help_text='Closing paragraph or takeaway', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='intro',
            field=models.TextField(blank=True, help_text='Introduction paragraph', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='section1_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='section1_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='section2_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='section2_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='section3_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='section3_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.TextField(help_text='Short summary for blog cards or preview.'),
        ),
    ]
