# Generated by Django 5.2.4 on 2025-07-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='comment_count',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
