# Generated by Django 5.2.4 on 2025-07-16 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_remove_project_demo_link_remove_project_github_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='conclusion',
            new_name='paragraph1',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='intro',
            new_name='paragraph2',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='process',
            new_name='paragraph3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='result',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.project')),
            ],
        ),
    ]
