# Generated by Django 5.2.4 on 2025-07-16 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_rename_conclusion_project_paragraph1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='paragraph1',
            new_name='conclusion',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='paragraph2',
            new_name='intro',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='paragraph3',
            new_name='process',
        ),
        migrations.AddField(
            model_name='project',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/screenshots/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='backend.project'),
        ),
    ]
